module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'welcome',
    },
    {
      type: 'doc',
      id: 'core/installation',
    },
    {
      type: 'doc',
      id: 'core/getting-started',
    },
    {
      type: 'category',
      label: 'Setup',
      items: [
        'core/backup',
        'core/bastion',
        'core/commands',
        'core/storage',
        'core/terraform',
        'core/tor'
      ],
    },
    {
      type: 'category',
      label: 'Software',
      items: [
        'software/adguardhome',
        'software/airsonic',
        'software/apache2',
        'software/authelia',
        'software/barcodebuddy',
        'software/beets',
        'software/bitwarden',
        'software/bookstack',
        'software/bulletnotes',
        'software/calibre',
        'software/chowdown',
        'software/codeserver',
        'software/codimd',
        'software/darksky',
        'software/digikam',
        'software/docs',
        'software/drone',
        'software/duckdns',
        'software/duplicati',
        'software/elkstack',
        'software/emby',
        'software/erpnext',
        'software/ethercalc',
        'software/factorio',
        'software/firefly',
        'software/folding_at_home',
        'software/freshrss',
        'software/funkwhale',
        'software/ghost',
        'software/gitea',
        'software/gitlab',
        'software/gotify',
        'software/grafana',
        'software/grocy',
        'software/guacamole',
        'software/hastebin',
        'software/healthchecks',
        'software/heimdall',
        'software/homeassistant',
        'software/homebridge',
        'software/homedash',
        'software/hubzilla',
        'software/huginn',
        'software/inventario',
        'software/invoiceninja',
        'software/jackett',
        'software/jellyfin',
        'software/jenkins',
        'software/keycloak',
        'software/kibitzr',
        'software/kutt',
        'software/lazylibrarian',
        'software/lidarr',
        'software/mailu',
        'software/mashio',
        'software/massivedecks',
        'software/matomo',
        'software/matterbridge',
        'software/mayan',
        'software/minecraft',
        'software/minecraftbedrockserver',
        'software/miniflux',
        'software/minio',
        'software/monica',
        'software/mstream',
        'software/mylar',
        'software/n8n',
        'software/netdata',
        'software/nextcloud',
        'software/nodered',
        'software/octoprint',
        'software/ombi',
        'software/openldap',
        'software/openvpn',
        'software/organizr',
        'software/ownphotos',
        'software/paperless',
        'software/peertube',
        'software/photoprism',
        'software/pihole',
        'software/piwigo',
        'software/pixelfed',
        'software/pleroma',
        'software/plex',
        'software/poli',
        'software/portainer',
        'software/privatebin',
        'software/qbittorrent',
        'software/radarr',
        'software/readarr',
        'software/rsshub',
        'software/sabnzbd',
        'software/samba',
        'software/searx',
        'software/shinobi',
        'software/sickchill',
        'software/simply-shorten',
        'software/snibox',
        'software/sonarr',
        'software/speedtest',
        'software/statping',
        'software/sui',
        'software/syncthing',
        'software/system-cockpit',
        'software/taisun',
        'software/tautulli',
        'software/teedy',
        'software/thelounge',
        'software/tick',
        'software/tiddlywiki',
        'software/transmission',
        'software/trilium',
        'software/turtl',
        'software/ubooquity',
        'software/unificontroller',
        'software/wallabag',
        'software/watchtower',
        'software/webdavserver',
        'software/webtrees',
        'software/webvirtmgr',
        'software/wekan',
        'software/wificard',
        'software/zammad',
        'software/zulip'
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'dev/adding-services',
        'CONTRIBUTING',
        'dev/tips'
      ],
    },
    {
      type: 'category',
      label: 'About',
      items: [
        'about',
        'jobs',
        'contact',
        'code-of-conduct',
        'legal',
        'CHANGELOG'
      ],
    },
  ],
};
